CREATE TABLE IF NOT EXISTS LINKS(
    ID INT NOT NULL UNIQUE AUTO_INCREMENT,
    TITLE VARCHAR (255),
    ADDRESS VARCHAR (255),
    USERID INT,
    FOREIGN KEY (USERID) REFERENCES USERS(ID),
    PRIMARY KEY (ID)
)